# Generated by Django 4.0.3 on 2022-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antibody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_num', models.CharField(max_length=200, null=True, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('host', models.CharField(choices=[('Rabbit', 'Rabbit'), ('Mouse', 'Mouse'), ('Rat', 'Rat'), ('Goat', 'Goat'), ('Horse', 'Horse'), ('Chicken', 'Chicken'), ('Guinea Pig', 'Guinea Pig'), ('Other', 'Other')], max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('recommended_WB_concentration', models.CharField(blank=True, max_length=200, null=True)),
                ('recommended_IHC_concentration', models.CharField(blank=True, max_length=200, null=True)),
                ('recommended_IHCp_concentration', models.CharField(blank=True, max_length=200, null=True)),
                ('recommended_IF_concentration', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
