# Generated by Django 4.0.3 on 2022-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdb', '0002_antibodyarc_antibodyind'),
    ]

    operations = [
        migrations.AddField(
            model_name='antibody',
            name='production',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antibodyarc',
            name='production',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='antibodyind',
            name='date_received',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='antibodyind',
            name='exp_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
